name: continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DB_HOST: localhost
  DB_PORT: 5432
  DB_URL: postgres://postgres:null@127.0.0.1:5432
  JWT_SECRET: 748384638011979397293gsdgs3828ashgka33

jobs:
  linting:
    name: Linting the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Run linting
        run: yarn lint

  testing:
    name: Testing the code
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
      # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup Node
      - uses: actions/setup-node@v1
        with:
          node-version: "17.8"

      - name: Installing Dependencies
        run: yarn

      - name: testing our app
        run: yarn test